package main

// FROM
// https://wiki.openraildata.com/index.php/Darwin:Cancellation_reason_codes_and_text
// https://wiki.openraildata.com/index.php/Darwin:Late_Running_reason_codes_and_text

var CancellationReasons = map[int]string{
    100: "This train has been cancelled because of a broken down train",
    101: "This train has been cancelled because of a delay on a previous journey",
    102: "This train has been cancelled because of a derailed train",
    104: "This train has been cancelled because of a fire at a station",
    105: "This train has been cancelled because of a fire at a station earlier",
    106: "This train has been cancelled because of a landslip",
    107: "This train has been cancelled because of a line-side fire",
    108: "This train has been cancelled because of a member of train crew being unavailable",
    109: "This train has been cancelled because of a passenger being taken ill",
    110: "This train has been cancelled because of a passenger having been taken ill earlier",
    111: "This train has been cancelled because of a person hit by a train",
    112: "This train has been cancelled because of a person hit by a train earlier",
    113: "This train has been cancelled because of a problem at a level crossing",
    114: "This train has been cancelled because of a problem currently under investigation",
    115: "This train has been cancelled because of a problem near the railway",
    116: "This train has been cancelled because of a problem with a river bridge",
    117: "This train has been cancelled because of a problem with line side equipment",
    118: "This train has been cancelled because of a security alert",
    119: "This train has been cancelled because of a train derailed earlier",
    120: "This train has been cancelled because of a train fault",
    121: "This train has been cancelled because of a train late from the depot",
    122: "This train has been cancelled because of a train late from the depot earlier",
    123: "This train has been cancelled because of a trespass incident",
    124: "This train has been cancelled because of a vehicle striking a bridge",
    125: "This train has been cancelled because of a vehicle striking a bridge earlier",
    126: "This train has been cancelled because of an earlier broken down train",
    128: "This train has been cancelled because of an earlier landslip",
    129: "This train has been cancelled because of an earlier line-side fire",
    130: "This train has been cancelled because of an earlier operating incident",
    131: "This train has been cancelled because of an earlier problem at a level crossing",
    132: "This train has been cancelled because of an earlier problem near the railway",
    133: "This train has been cancelled because of an earlier problem with a river bridge",
    134: "This train has been cancelled because of an earlier problem with line side equipment",
    135: "This train has been cancelled because of an earlier security alert",
    136: "This train has been cancelled because of an earlier train fault",
    137: "This train has been cancelled because of an earlier trespass incident",
    138: "This train has been cancelled because of an obstruction on the line",
    139: "This train has been cancelled because of an obstruction on the line earlier",
    140: "This train has been cancelled because of an operating incident",
    141: "This train has been cancelled because of an unusually large passenger flow",
    142: "This train has been cancelled because of an unusually large passenger flow earlier",
    143: "This train has been cancelled because of animals on the line",
    144: "This train has been cancelled because of animals on the line earlier",
    145: "This train has been cancelled because of congestion caused by earlier delays",
    146: "This train has been cancelled because of disruptive passengers",
    147: "This train has been cancelled because of disruptive passengers earlier",
    148: "This train has been cancelled because of earlier electrical supply problems",
    149: "This train has been cancelled because of earlier emergency engineering works",
    150: "This train has been cancelled because of earlier industrial action",
    151: "This train has been cancelled because of earlier overhead wire problems",
    152: "This train has been cancelled because of earlier over-running engineering works",
}

var LateRunningReasons = map[int]string{
    100: "This train has been delayed by a broken down train",
    101: "This train has been delayed by a delay on a previous journey",
    102: "This train has been delayed by a derailed train",
    104: "This train has been delayed by a fire at a station",
    105: "This train has been delayed by a fire at a station earlier",
    106: "This train has been delayed by a landslip",
    107: "This train has been delayed by a line-side fire",
    108: "This train has been delayed by a member of train crew being unavailable",
    109: "This train has been delayed by a passenger being taken ill",
    110: "This train has been delayed by a passenger having been taken ill earlier",
    111: "This train has been delayed by a person hit by a train",
    112: "This train has been delayed by a person hit by a train earlier",
    113: "This train has been delayed by a problem at a level crossing",
    114: "This train has been delayed by a problem currently under investigation",
    115: "This train has been delayed by a problem near the railway",
    116: "This train has been delayed by a problem with a river bridge",
    117: "This train has been delayed by a problem with line side equipment",
    118: "This train has been delayed by a security alert",
    119: "This train has been delayed by a train derailed earlier",
    120: "This train has been delayed by a train fault",
    121: "This train has been delayed by a train late from the depot",
    122: "This train has been delayed by a train late from the depot earlier",
    123: "This train has been delayed by a trespass incident",
    124: "This train has been delayed by a vehicle striking a bridge",
    125: "This train has been delayed by a vehicle striking a bridge earlier",
    126: "This train has been delayed by an earlier broken down train",
    128: "This train has been delayed by an earlier landslip",
    129: "This train has been delayed by an earlier line-side fire",
    130: "This train has been delayed by an earlier operating incident",
    131: "This train has been delayed by an earlier problem at a level crossing",
    132: "This train has been delayed by an earlier problem near the railway",
    133: "This train has been delayed by an earlier problem with a river bridge",
    134: "This train has been delayed by an earlier problem with line side equipment",
    135: "This train has been delayed by an earlier security alert",
    136: "This train has been delayed by an earlier train fault",
    137: "This train has been delayed by an earlier trespass incident",
    138: "This train has been delayed by an obstruction on the line",
    139: "This train has been delayed by an obstruction on the line earlier",
    140: "This train has been delayed by an operating incident",
    141: "This train has been delayed by an unusually large passenger flow",
    142: "This train has been delayed by an unusually large passenger flow earlier",
    143: "This train has been delayed by animals on the line",
    144: "This train has been delayed by animals on the line earlier",
    145: "This train has been delayed by congestion caused by earlier delays",
    146: "This train has been delayed by disruptive passengers",
    147: "This train has been delayed by disruptive passengers earlier",
    148: "This train has been delayed by earlier electrical supply problems",
    149: "This train has been delayed by earlier emergency engineering works",
    150: "This train has been delayed by earlier industrial action",
    151: "This train has been delayed by earlier overhead wire problems",
    152: "This train has been delayed by earlier over-running engineering works",
}
